config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  mount Ckeditor::Engine => '/ckeditor'

  namespace :panel do
    root to: "dashboard#index"

    resources :events #actividades
    resources :grades #notas
    resources :school_classes #grados (1ero, ....)
    resources :subjects #materias
    resources :periods #periodos
    resources :stages #etapa escolar
    resources :contacts
    resources :profile, only: [:edit, :update]
    resources :users
  end
  root to: "panel/dashboard#index"

end

app/views/layouts/admin/_left_bar.haml
/ Right sidemenu
#skin-select.fixed-nest
  / Toggle sidemenu icon button
  %a#toggle
  / End of Toggle sidemenu icon button
  .skin-part
    #tree-wrap
      / Profile
      .profile

        = link_to image_tag('admin/school.png'), panel_root_url
        = link_to panel_root_url() do
          %h3
            COLEGIO
            %small ADMIN
      / End of Profile
      / Menu sidebar begin
      .fixed-nest-sidebar
        .slimScrollDiv
          .side-bar.sidebar-fixed
            %ul#menu-showhide.topnav.slicknav
              %li
                = link_to panel_root_url, class: 'tooltip-tip', id: 'menu-select', title: 'Dashboard' do
                  %i.palette-Deep-Purple-700.bg.ti-desktop
                  %span Dashboard
              %li
                %a.tooltip-tip{:href => "#", :title => "Notas"}
                  %i.palette-Red-400.bg.ti-pencil
                  %span
                    Notas
                %ul
                  %li
                    = link_to "Listado", panel_grades_url()
                  %li
                    = link_to "Nueva nota", new_panel_grade_url()

              %li
                %a.tooltip-tip{:href => "#", :title => "Grados"}
                  %i.palette-Indigo-700.bg.ti-layout
                  %span
                    Grados
                    -#
                      %small.side-menu-noft New
                %ul
                  %li
                    = link_to "Listado", panel_school_classes_url()
                  %li
                    = link_to "Nuevo grado", new_panel_school_class_url()
              %li
                %a.tooltip-tip{:href => "#", :title => "Materias"}
                  %i.intial.palette-Blue-700.bg.ti-book
                  %span Materias
                %ul
                  %li
                    = link_to "Listado", panel_subjects_url()
                  %li
                    = link_to "Nueva materia", new_panel_subject_url()
              %li
                %a{:href => "#", :title => "Etapas Escolares"}
                  %i.intial.palette-Green-700.bg.ti-briefcase
                  %span
                    Etapas Escolares
                    -#
                      %small.side-menu-noft.bg-blue hot
                %ul
                  %li
                    = link_to "Listado", panel_stages_url()
                  %li
                    = link_to "Nueva etapa", new_panel_stage_url()
              %li
                %a.tooltip-tip{:href => "#", :title => "Actividades"}
                  %i.intial.palette-Orange-700.ti-time.bg
                  %span Actividades
                %ul
                  %li
                    = link_to "Listado", panel_events_url()
                  %li
                    = link_to "Nueva actividad", new_panel_event_url()

              %li
                %a.tooltip-tip{:href => "#", :title => "Contactos (Estudiantes)"}
                  %i.intial.palette-Amber-700.bg.ti-thumb-up
                  %span Contactos (Estudiantes)
                %ul
                  %li
                    = link_to "Listado", panel_contacts_url()
                  %li
                    = link_to "Nuevo contacto", new_panel_contact_url()

              - if current_user.has_role?("admin")
                %li
                  %a.tooltip-tip{:href => "#", :title => "Usuarios"}
                    %i.intial.palette-Green-200.bg.ti-user
                    %span Usuarios
                  %ul
                    %li
                      = link_to "Listado", panel_users_url()
                    %li
                      = link_to "Nuevo usuario", new_panel_user_url()
              - elsif current_user.has_role?("teacher")

                %li
                  %a.tooltip-tip{:href => "#", :title => "Estudiantes"}
                    %i.intial.palette-Green-200.bg.ti-user
                    %span Estudiantes
                  %ul
                    %li
                      = link_to "Listado", panel_users_url()
                    %li
                      = link_to "Nuevo estudiante", new_panel_user_url()
              -#
                %li
                  %a.tooltip-tip{:href => "#", :title => "Adjuntos"}
                    %i.intial.palette-Brown-200.bg.ti-folder
                    %span Adjuntos
                  %ul
                    %li
                      = link_to "Categorías para adjuntos", panel_attachment_categories_url()
                    %li
                      = link_to "Adjuntos", panel_attachments_url()


          / end of Menu sidebar
          / bottom chat

app/views/layouts/admin/_notice.haml
- if flash[:notice]
  .success.callout{"data-closable" => "slide-out-right"}
    = flash[:notice]
    %button.close-button{"aria-label" => "Dismiss alert", "data-close" => "", :type => "button"}
      %span{"aria-hidden" => "true"} &times;

app/views/layouts/admin/_right_bar.haml
#offCanvas.bg-transparent.off-canvas.position-right{"data-off-canvas" => "", "data-position" => "right"}
  / Close button
  %button.close-button{"aria-label" => "Close menu", "data-close" => "", :type => "button"}
    %span{"aria-hidden" => "true"} ×
  .off-canvas-content{"data-off-canvas-content" => ""}
    / Menu
    %ul.nav.navbar-stacked
      %li
        %a{:href => "#"}
          %span.palette-Black-100.bg.ti-menu-alt>
          Notifications
      %li
        %a{:href => "#"}
          %span.palette-Deep-Purple-100.bg.ti-menu-alt
          %i.ti-more-alt
          %span.palette-Deep-Purple-200.bg.ti-shopping-cart-full
          %i.ti-more-alt
          %span.palette-Deep-Purple-400.bg.ti-gift
          %i.ti-more-alt
          %span.palette-Deep-Purple-600.bg.ti-truck
          %i.ti-more-alt
          = succeed "Shipping" do
            %span.palette-Deep-Purple-800.bg.ti-home
          %strong Robert Langdon
          is completed!
          %small 1m
      %li
        %a{:href => "#"}
          %span.palette-Blue-A100.bg.ti-user>
          Meet new user
          %strong Lilian Meirs
          %small 23m
      %li
        %a{:href => "#"}
          %span.palette-Red-A400.bg.ti-cloud-down
          %strong Robert
          added new request for ne item for refund
          %small 34m
      %li
        %a{:href => "#"}
          %span.palette-Orange-200.bg.ti-menu-alt
          %i.ti-more-alt
          %span.palette-Orange-400.bg.ti-shopping-cart-full
          %i.ti-more-alt
          %span.palette-Orange-600.bg.ti-gift
          = succeed "Shipping" do
            %br/
          %strong Robert Langdon
          is completed!
          %small 40m
      %li
        %a{:href => "#"}
          %span.palette-Amber-500.bg.ti-comment-alt>
          Mike Nilson commented Post
          %br/
          Like this one! Keep going!
          %small 50m
      %li
        %a{:href => "#"}
          %span.palette-Cyan-300.bg.ti-shopping-cart-full>
          Amazing!
          %strong Mike Nilson
          just purchased Your item
          %small 1h
      %li
        %a{:href => "#"}
          %span.palette-Light-Green-500.bg.ti-image
          %strong Lilian Meirs
          Posting new image cover, and just got 2.000 likes
          %br/
          %img{:alt => "", :src => "http://placehold.it/2000x2000"}/
          %small 1h 12m
      %li
        %a{:href => "#"}
          %span.palette-Amber-500.bg.ti-comment-alt>
          Mike Nilson commented Post
          %br/
          Like this one! Keep going!
          %small 1h 39
      %li
        %a{:href => "#"}
          %span.palette-Cyan-300.bg.ti-shopping-cart-full>
          Amazing!
          %strong Mike Nilson
          just purchased Your item
          %br/
          %img{:alt => "", :src => "http://placehold.it/2000x2000"}/
          %small 1h 45m
      %li
        %a{:href => "#"}
          %span.palette-Cyan-300.bg.ti-shopping-cart-full>
          Amazing!
          %strong Mike Nilson
          just purchased Your item
          %small 23m
      %li
        %a{:href => "#"}
          %span.palette-Amber-500.bg.ti-comment-alt>
          Mike Nilson commented Post
          %br/
          Like this one! Keep going!
          %small 2h

app/views/layouts/admin/_top_bar.haml
.top-bar-left
  %ul.dropdown.menu.menu-profile.bg-white
    / PROFILE
    %li.bg-white.user-icon-profile
      %i.intial.palette-Indigo-700.bg.ti-user.rounder
    %li.bg-white
      %a.bg-white.text-gray{"data-toggle" => "profile-dropdown"}
        Hola, #{current_user.full_name}
      #profile-dropdown.dropdown-pane.dropdown-pane-nest.profile-nest.bottom{"data-auto-focus" => "true", "data-dropdown" => ""}
        %ul.menu.vertical.dropdown.profile-dropdown
          %li
            = link_to "" do
              =# edit_profile_url(current_user) do
              %i.ti-user.palette-Indigo-500.bg
              Perfil
              %span.text-aqua.fontello-record
          -# %li
          -#   %a{:href => "#"}
          -#     %i.ti-wallet.palette-Blue-700.bg
          -#     Accounts
          %li
            = link_to destroy_user_session_url do
              %i.ti-power-off.palette-Light-Blue-900.bg>
              Salir
    / end of PROFILE
.top-bar-right
  %ul.dropdown.vertical.medium-horizontal.menu.bg-white{"data-dropdown-menu" => ""}
    %li
      = link_to destroy_user_session_url do
        %i.ti-power-off.palette-Light-Blue-900.bg>
        Salir
    / Search | has-form wrapper
    -#
      %li.bg-white
        %form.navbar-form.navbar-left{:role => "search"}
          .dark
          %input.input-top{:placeholder => "search", :type => "text"}/
    / End Of Search | has-form wrapper
    / MESSAGE
    -#
      %li.bg-white
        %a.button.bg-white.float-right{"data-toggle" => "msg-dropdown"}
          %i.ti-agenda.palette-Pink-500.text
          %span.label.edumix-msg-noft.palette-Pink-500.bg 84
        #msg-dropdown.dropdown-pane.dropdown-pane-nest.bottom{"data-auto-focus" => "true", "data-dropdown" => ""}
          %ul.menu.vertical.dropdown.dropdown-wrap
            %li
              .top-dropdown-nest
                %span.label.round.bg-green MESSAGE
                %a{:href => "#"}
                  %h3.text-black
                    Big Boss
                    %b.text-red.fontello-record
                    %span
                      Just Now
                      %small
                  %p.text-black Important task!
            %li
              .slim-scroll
                %div
                  %a{:href => "#"}
                    %h3
                      Noel A. Riley
                      %b.text-green.fontello-record
                      %span
                        12:23
                        %small PM
                %div
                %p
                  Dua dua sayang adik kakak
                  %a{:href => "#"}
                    %h3
                      Shirley J. Carneal
                      %b.text-gray.fontello-record
                      %span
                        10:11
                        %small PM
                    %p Tiga tiga sayang kekasihku
                %div
                  %a{:href => "#"}
                    %h3
                      Paul L. Williamsr
                      %b.text-gray.fontello-record
                      %span Yesterday
                    %p Empat empat sayang semuanya
                %div
                  %a{:href => "#"}
                    %h3
                      William L. Wilcox
                      %b.text-gray.fontello-record
                      %span 2 Days Ago
                    %p Yang jomblo kasian deh lu
            %li.active.right
              %a{:href => "#"}
                .label.bg-white More...
      / end of MESSAGE
      / NOTIFICATION
      %li.bg-white
        %a.button.bg-white.float-right{"data-toggle" => "notf-dropdown"}
          %i.ti-bell.palette-Purple-500.text
          %span.label.edumix-noft.palette-Purple-500.bg 45
        #notf-dropdown.dropdown-pane.dropdown-pane-nest.bottom{"data-auto-focus" => "true", "data-dropdown" => ""}
          %ul.menu.vertical.dropdown.dropdown-wrap
            %li
              .top-dropdown-nest
                %span.label.round.bg-blue ALERT
                %a{:href => "#"}
                  %h3.text-black
                    Sticky Very Important
                    %span.text-red.fontello-record
                  %p.text-black 1 minute ago
            %li
              .slim-scroll
                %div
                  %i.ti-comments-smiley
                  %a{:href => "#"}
                    %h3
                      Announcements
                      %span.text-green.fontello-record
                    %p Just Now !
                %div
                  %i.fontello-attach-1
                  %a{:href => "#"}
                    %h3
                      Complete your profile
                      %span.text-yellow.fontello-record
                    %p 2 Minute Ago
                %div
                  %i.fontello-calendar-1
                  %a{:href => "#"}
                    %h3
                      New Schedule Realease
                      %span.text-yellow.fontello-record
                    %p 30 Minute ago
                %div
                  %i.fontello-database-1
                  %a{:href => "#"}
                    %h3
                      New Student Data
                      %span.text-orange.fontello-record
                    %p 1 Hour ago
                %div
                  %i.fontello-graduation-cap
                  %a{:href => "#"}
                    %h3
                      Graduate Student List
                      %span.fontello-record
                    %p 2 Days ago
            / end of NOTIFICATION
            %li.active.right
              %a{:href => "#"}
                .label.bg-white More...
      %li.bg-white
        %a.bg-white{"data-toggle" => "offCanvas"}
          %i.text-black.ti-menu
    / Right Nav Section

app/views/layouts/admin/application.html.haml
!!!
%html.no-js{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title School App Admin
    = csrf_meta_tags
    = stylesheet_link_tag 'admin/application', media: 'all'
    = javascript_include_tag 'admin/preload'
    =# %script{:src => "https://maps.googleapis.com/maps/api/js?key=AIzaSyDHt7vrI9b3Ze5nGXaCPrlaBzR-Saqg4G8"}
  %body
    #preloader
      #status  
    .off-canvas-wrapper.over-flow-hidden
      .off-canvas-wrapper-inner{"data-off-canvas-wrapper" => ""}
        .inner-wrap
          = render 'layouts/admin/left_bar'
          #paper-bg.wrap-fluid
            .title-bar{"data-hide-for" => "medium", "data-responsive-toggle" => "example-menu"}
              %button.menu-icon{"data-toggle" => "", :type => "button"}
              .title-bar-title Menu
            #example-menu.top-bar
              = render 'layouts/admin/top_bar'
              = render 'layouts/admin/notice'
            = yield
          = render 'layouts/admin/right_bar'
    = javascript_include_tag 'admin/application'